AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppviaRoleARN:
    Type: String
    Description: Fully-qualified ARN of the remote role
    Default: arn:aws:iam::730335310409:role/aws-reserved/sso.amazonaws.com/eu-west-2/AWSReservedSSO_WAFSupport_19c9bc61106389c3
  ManagedPolicyArns:
    Type: CommaDelimitedList
    Description: List of AWS managed policy ARNs to apply to the role
    Default: 'arn:aws:iam::aws:policy/SecurityAudit, arn:aws:iam::aws:policy/ReadOnlyAccess'
  ExternalID:
    Type: String
    Description: External ID shared between consumer and Appvia
  ExpiryDate:
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AppviaAuditRole
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AppviaRoleARN
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalID
      ManagedPolicyArns: !Ref ManagedPolicyArns
      Policies:
        - PolicyName: PermissionDeadline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'
                Condition:
                  DateGreaterThan:
                    "aws:CurrentTime": !Ref ExpiryDate
